In [1]:
import numpy as np

In [2]:
mylist=[i for i in range(2,51)]
array=np.array(mylist[::3])
array

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47, 50])

In [3]:
list1=[]
list2=[]
print('Enter the elements for array 1')
for i in range(5):
    list1inp=int(input())
    list1.append(list1inp)

print('Enter the elements for array 2')   
for i in range(5):
    list2inp=int(input())
    list2.append(list2inp)

arr1=np.array(list1)
arr2=np.array(list2)
conc_arr=np.concatenate([arr1,arr2])
print(conc_arr)
sort_arr=np.sort(conc_arr)
print(sort_arr)

Enter the elements for array 1
6
5
7
3
4
Enter the elements for array 2
5
3
8
9
15
[ 6  5  7  3  4  5  3  8  9 15]
[ 3  3  4  5  5  6  7  8  9 15]


In [4]:
arr=np.array('''Enter the list''')
# to find dimensions
print(arr.ndim)
# to find the size
print(arr.size)

0
1


In [5]:
# enter the list from which you want to create the array
arrlist=[1,2,3,4,5,6,7,8,9]
# creating 1D Array
oneDArray=np.array(arrlist)
# converting 1D Array to 2D Array
twoDArray=oneDArray.reshape(3,3)
print(twoDArray)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
array1=np.array([[1,2,3],[7,8,9],[10,11,12]])
array2=np.array([[13,14,15],[16,17,18],[19,20,21]])
print(np.vstack((array1,array2)))
print(np.hstack((array1,array2)))

[[ 1  2  3]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]
 [19 20 21]]
[[ 1  2  3 13 14 15]
 [ 7  8  9 16 17 18]
 [10 11 12 19 20 21]]


In [13]:
array3=np.array([1,1,1,2,3,4,5,6,5,6,7,8,7,7,7,9,8,6])
unique,counts=np.unique(array3,return_counts=True)
for i,j in zip(unique,counts):
    print(f'{i} {j}')

1 3
2 1
3 1
4 1
5 2
6 3
7 4
8 2
9 1
